sudo: required
services:
  - docker
before_install:
  - docker build -f ./client/Dockerfile.dev -t buddhamagnet/client-tests ./client
script:
  - docker run buddhamagnet/client-tests npm run test -- --coverage
