sudo: required
services:
  - docker
before_install:
  - docker build -f ./client/Dockerfile.dev -t buddhamagnet/client-tests ./client
script:
  - docker run buddhamagnet/client-tests npm run test -- --coverage
after_success:
  - docker build -t buddhamagnet/multi-client ./client
  - docker build -t buddhamagnet/multi-server ./server
  - docker build -t buddhamagnet/multi-worker ./worker
  - docker build -t buddhamagnet/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passwd-stdin
